stages:
  - clean
  - package
  - deploy

clean:
  tags:
    - Shell-Maven
  stage: clean
  script:
    - mvn clean

package:
  tags:
    - Shell-Maven
  stage: package
  script:
    - mvn package
  artifacts:
    name: exepath
    paths: 
      - target\jfx\native\Integration_Project_Frontend_1.0.exe

deploy:
  tags:
    - Shell-Maven
  stage: deploy
  script:
    - copy target/jfx/native/Integration_Project_Frontend_1.0.exe 
    - echo "Implementation of the app"

